JENKINS_TESTTYPES:
  - bareos-client-only
  - bareos-postgresql
  - univention-bareos
  - bareos-universal-client

OS:
  FreeBSD:
    "12.2":
      TYPE: freebsd
      ARCH:
        - amd64
      PROJECTPACKAGES:
        amd64:
           - bareos-freebsd
    "13.0":
      TYPE: freebsd
      ARCH:
        - amd64
      PROJECTPACKAGES:
        amd64:
           - bareos-freebsd

